/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import javax.swing.JFrame;


/**
 *
 * @author Zain
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titlelabel = new javax.swing.JLabel();
        TitleTextField = new javax.swing.JTextField();
        authLabel = new javax.swing.JLabel();
        publabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        CopiesLabel = new javax.swing.JLabel();
        AuthorTextField = new javax.swing.JTextField();
        PublisherTextField = new javax.swing.JTextField();
        SubTextField = new javax.swing.JTextField();
        CopiesTextField = new javax.swing.JTextField();
        ItemSelectionbox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MessageLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Item");

        titlelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titlelabel.setText("Title");

        TitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextFieldActionPerformed(evt);
            }
        });

        authLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        authLabel.setText("Author");

        publabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        publabel.setText("Publisher");

        subLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subLabel.setText("Subject");

        CopiesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CopiesLabel.setText("Copies");

        ItemSelectionbox.setMaximumRowCount(2);
        ItemSelectionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOOK", "DVD" }));
        ItemSelectionbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemSelectionboxItemStateChanged(evt);
            }
        });

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Select Item");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subLabel)
                            .addComponent(CopiesLabel)
                            .addComponent(authLabel)
                            .addComponent(titlelabel)
                            .addComponent(jLabel6)
                            .addComponent(publabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AuthorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(SubTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(PublisherTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(TitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ItemSelectionbox, 0, 150, Short.MAX_VALUE)
                            .addComponent(CopiesTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(MessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemSelectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titlelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subLabel)
                    .addComponent(SubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CopiesLabel)
                    .addComponent(CopiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TitleTextFieldActionPerformed

    private void ItemSelectionboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ItemSelectionboxItemStateChanged
        // TODO add your handling code here:
        if(ItemSelectionbox.getSelectedIndex()==1)
        {   
            CopiesTextField.setVisible(true);
            TitleTextField.setVisible(true);
            SubTextField.setVisible(true);
            CopiesLabel.setVisible(true);
            subLabel.setVisible(true);
            titlelabel.setVisible(true);
            
            AuthorTextField.setVisible(false);
            PublisherTextField.setVisible(false);
            authLabel.setVisible(false);
            publabel.setVisible(false);
        }
        else
        {
            AuthorTextField.setVisible(true);
            PublisherTextField.setVisible(true);
            authLabel.setVisible(true);
            publabel.setVisible(true);
        }
    }//GEN-LAST:event_ItemSelectionboxItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(CopiesTextField.getText().equals("") ||
                SubTextField.getText().equals("") ||
                TitleTextField.getText().equals(""))
        {
            if(ItemSelectionbox.getSelectedIndex()==0)
            {
                if(AuthorTextField.getText().equals("") ||
                        PublisherTextField.getText().equals(""))
                {
                    MessageLabel.setText("All Fields Required!");
                }
            }
            else
            {
                MessageLabel.setText("All Fields Required!");
            }
        }
        else
        {
            Connector con=new Connector();
            if(ItemSelectionbox.getSelectedIndex()==0)
            {
                
                con.AddBook(TitleTextField.getText(), AuthorTextField.getText(), 
                    PublisherTextField.getText(), SubTextField.getText(),
                    Integer.parseInt(CopiesTextField.getText()));
            }
            else
            {
                con.AddDvd(TitleTextField.getText(), SubTextField.getText(), 
                        Integer.parseInt(CopiesTextField.getText()));
            }
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Message("Item Added Successfully").setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Connector con=new Connector();
        User u=Connector.getCurrentUser();
        int type=u.type;
        switch(type)
        {
            case 2:
                    java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                              new ClerkMenu().setVisible(true);
                         }
                     }); break;
            case 3:
                java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                             new LibrarianMenu().setVisible(true);
                         }
                     }); break;                 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorTextField;
    private javax.swing.JLabel CopiesLabel;
    private javax.swing.JTextField CopiesTextField;
    private javax.swing.JComboBox<String> ItemSelectionbox;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField PublisherTextField;
    private javax.swing.JTextField SubTextField;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.JLabel authLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel publabel;
    private javax.swing.JLabel subLabel;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables
}
