/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Zain
 */
public class EditUser extends javax.swing.JFrame {

    /**
     * Creates new form EditUser
     */
    public EditUser() {
        initComponents();
        AddLabel.setVisible(false);
        AddTextField.setVisible(false);
        EmailLabel.setVisible(false);
        EmailTextField.setVisible(false);
        NameLabel.setVisible(false);
        NameTextField.setVisible(false);
        PhLabel.setVisible(false);
        PhTextField.setVisible(false);
    }
    
    public boolean isNumeric(String strNum) {
        try {
            double d = Double.parseDouble(strNum);
        } 
        catch (NumberFormatException | NullPointerException nfe) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        AddLabel = new javax.swing.JLabel();
        PhLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        AddTextField = new javax.swing.JTextField();
        PhTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UserIdTextField = new javax.swing.JTextField();
        UserIdCheckButton = new javax.swing.JButton();
        MsgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Edit User Details");

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLabel.setText("Name");

        EmailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        AddLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddLabel.setText("Address");

        PhLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PhLabel.setText("Phone No.");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Enter User ID");

        UserIdCheckButton.setText("Check");
        UserIdCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIdCheckButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel)
                            .addComponent(EmailLabel)
                            .addComponent(AddLabel)
                            .addComponent(PhLabel)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MsgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(UserIdTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(51, 51, 51)
                        .addComponent(UserIdCheckButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UserIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserIdCheckButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MsgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLabel)
                    .addComponent(AddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhLabel)
                    .addComponent(PhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(UpdateButton)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserIdCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIdCheckButtonActionPerformed
        // TODO add your handling code here:
        User RU=project.LibraryManagementSystem.searchUser(Integer.parseInt(UserIdTextField.getText()));
        if(!isNumeric(UserIdTextField.getText()))
        {
            MsgLabel.setText("Please enter numeric value");
            AddLabel.setVisible(false);
            AddTextField.setVisible(false);
            EmailLabel.setVisible(false);
            EmailTextField.setVisible(false);
            NameLabel.setVisible(false);
            NameTextField.setVisible(false);
            PhLabel.setVisible(false);
            PhTextField.setVisible(false);
        }
        else if(RU==null)
        {
            MsgLabel.setText("User dose not exist.");
            AddLabel.setVisible(false);
            AddTextField.setVisible(false);
            EmailLabel.setVisible(false);
            EmailTextField.setVisible(false);
            NameLabel.setVisible(false);
            NameTextField.setVisible(false);
            PhLabel.setVisible(false);
            PhTextField.setVisible(false);
        }
        else
        {
            AddLabel.setVisible(true);
            AddTextField.setVisible(true);
            EmailLabel.setVisible(true);
            EmailTextField.setVisible(true);
            NameLabel.setVisible(true);
            NameTextField.setVisible(true);
            PhLabel.setVisible(true);
            PhTextField.setVisible(true);
        }
    }//GEN-LAST:event_UserIdCheckButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        Connector con=new Connector();
        User u=con.getCurrentUser();
        int id=Integer.parseInt(UserIdTextField.getText());
        User RU=project.LibraryManagementSystem.searchUser(id);
        if(u.type==2)
        {
            if(RU.type==1)
            {
                con.EditUser(id,NameTextField.getText(),EmailTextField.getText(),
                        PhTextField.getText(),AddTextField.getText(),RU.type);
            }
            else
            {
                MsgLabel.setText("Cannot edit this user");
                AddLabel.setVisible(false);
                AddTextField.setVisible(false);
                EmailLabel.setVisible(false);
                EmailTextField.setVisible(false);
                NameLabel.setVisible(false);
                NameTextField.setVisible(false);
                PhLabel.setVisible(false);
                PhTextField.setVisible(false);
            }
        }
        else if(u.type==3)
        {
            con.EditUser(id,NameTextField.getText(),EmailTextField.getText(),
                        PhTextField.getText(),AddTextField.getText(),RU.type);
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Message("User edit Successfully").setVisible(true);
            }
        });
        }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Connector con=new Connector();
        User u=Connector.getCurrentUser();
        int type=u.type;
        switch(type)
        {
            case 2:
                    java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                              new ClerkMenu().setVisible(true);
                         }
                     }); break;
            case 3:
                java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                             new LibrarianMenu().setVisible(true);
                         }
                     }); break;                 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JTextField AddTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel MsgLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PhLabel;
    private javax.swing.JTextField PhTextField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UserIdCheckButton;
    private javax.swing.JTextField UserIdTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
