/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Zain
 */
public class LibrarianMenu extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianMenu
     */
    public LibrarianMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddItem = new javax.swing.JButton();
        RemoveItem = new javax.swing.JButton();
        EditItem = new javax.swing.JButton();
        AddUser = new javax.swing.JButton();
        RemoveUser = new javax.swing.JButton();
        EditUser = new javax.swing.JButton();
        CheckOutItem = new javax.swing.JButton();
        CheckInItem = new javax.swing.JButton();
        SearchItem = new javax.swing.JButton();
        BorrowerDetailsButton = new javax.swing.JButton();
        ClerkDetails = new javax.swing.JButton();
        BookDetails = new javax.swing.JButton();
        LoanDetails = new javax.swing.JButton();
        LibrarianDetails = new javax.swing.JButton();
        DvdDetails = new javax.swing.JButton();
        SearchLoan = new javax.swing.JButton();
        UserSearch = new javax.swing.JButton();
        ChangeUserPassword = new javax.swing.JButton();
        ChangeYourPassword = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ViewProfileInfo = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        AllDvdAvailable = new javax.swing.JButton();
        AllBookAvailable = new javax.swing.JButton();
        AllPendingLoans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        AddItem.setText("Add Item");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        RemoveItem.setText("Remove Item");
        RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItemActionPerformed(evt);
            }
        });

        EditItem.setText("Edit Item");
        EditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditItemActionPerformed(evt);
            }
        });

        AddUser.setText("Add User");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        RemoveUser.setText("Remove User");
        RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserActionPerformed(evt);
            }
        });

        EditUser.setText("Edit User");
        EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserActionPerformed(evt);
            }
        });

        CheckOutItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CheckOutItem.setText("Check Out Item");
        CheckOutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutItemActionPerformed(evt);
            }
        });

        CheckInItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CheckInItem.setText("Check In Item");
        CheckInItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInItemActionPerformed(evt);
            }
        });

        SearchItem.setText("Search Item");
        SearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchItemActionPerformed(evt);
            }
        });

        BorrowerDetailsButton.setText("Borrower's Details");
        BorrowerDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowerDetailsButtonActionPerformed(evt);
            }
        });

        ClerkDetails.setText("Clerk's Details");
        ClerkDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClerkDetailsActionPerformed(evt);
            }
        });

        BookDetails.setText("Book's  Details");
        BookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDetailsActionPerformed(evt);
            }
        });

        LoanDetails.setText("Loan's  Details");
        LoanDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanDetailsActionPerformed(evt);
            }
        });

        LibrarianDetails.setText("Librarian's Details");
        LibrarianDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarianDetailsActionPerformed(evt);
            }
        });

        DvdDetails.setText("DVD's  Details");
        DvdDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DvdDetailsActionPerformed(evt);
            }
        });

        SearchLoan.setText("Search Loan");

        UserSearch.setText("Search User");
        UserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSearchActionPerformed(evt);
            }
        });

        ChangeUserPassword.setText("Change User's  Password");
        ChangeUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeUserPasswordActionPerformed(evt);
            }
        });

        ChangeYourPassword.setText("Change Your  Password");
        ChangeYourPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeYourPasswordActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        ViewProfileInfo.setText("View Profile Info");
        ViewProfileInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileInfoActionPerformed(evt);
            }
        });

        jButton32.setText("All Loans Taken by Me");

        jButton33.setText("My Pending Loans");

        AllDvdAvailable.setText("All DVDs Availabale");
        AllDvdAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDvdAvailableActionPerformed(evt);
            }
        });

        AllBookAvailable.setText("All Books Availabale");
        AllBookAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllBookAvailableActionPerformed(evt);
            }
        });

        AllPendingLoans.setText("All Pending Loans");
        AllPendingLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllPendingLoansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BorrowerDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClerkDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DvdDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LibrarianDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoanDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CheckInItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangeYourPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangeUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllBookAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckOutItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(ViewProfileInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchLoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AllDvdAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AllPendingLoans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RemoveUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItem)
                    .addComponent(AddUser))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveItem)
                    .addComponent(RemoveUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditItem)
                    .addComponent(EditUser))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckInItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrowerDetailsButton)
                    .addComponent(BookDetails)
                    .addComponent(SearchItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClerkDetails)
                    .addComponent(DvdDetails)
                    .addComponent(SearchLoan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LibrarianDetails)
                    .addComponent(LoanDetails)
                    .addComponent(UserSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeUserPassword)
                    .addComponent(jButton33))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeYourPassword)
                    .addComponent(ViewProfileInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton32)
                    .addComponent(AllDvdAvailable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllBookAvailable)
                    .addComponent(AllPendingLoans))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }//GEN-LAST:event_AddUserActionPerformed

    private void AllDvdAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDvdAvailableActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllDvdAvailable().setVisible(true);
            }
        });
    }//GEN-LAST:event_AllDvdAvailableActionPerformed

    private void AllBookAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllBookAvailableActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllBookAvailable().setVisible(true);
            }
        });
    }//GEN-LAST:event_AllBookAvailableActionPerformed

    private void AllPendingLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllPendingLoansActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllPendingLoans().setVisible(true);
            }
        });
    }//GEN-LAST:event_AllPendingLoansActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        Connector.setCurrentUser(null);
        this.setVisible(false);
        this.setDefaultCloseOperation(LibrarianMenu.DO_NOTHING_ON_CLOSE);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void SearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.setDefaultCloseOperation(ClerkMenu.DO_NOTHING_ON_CLOSE);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchItems().setVisible(true);
            }
        });
    }//GEN-LAST:event_SearchItemActionPerformed

    private void CheckInItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInItemActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckInItem().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_CheckInItemActionPerformed

    private void CheckOutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutItem().setVisible(true);
            }
        });
    }//GEN-LAST:event_CheckOutItemActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }//GEN-LAST:event_AddItemActionPerformed

    private void RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveItem().setVisible(true);
            }
        });
    }//GEN-LAST:event_RemoveItemActionPerformed

    private void EditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditItemActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItem().setVisible(true);
            }
        });
    }//GEN-LAST:event_EditItemActionPerformed

    private void RemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveUser().setVisible(true);
            }
        });
    }//GEN-LAST:event_RemoveUserActionPerformed

    private void EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUser().setVisible(true);
            }
        });
    }//GEN-LAST:event_EditUserActionPerformed

    private void BorrowerDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowerDetailsButtonActionPerformed
        // TODO add your handling code here:
        int gg=0;
        gg=3;
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails(1).setVisible(true);
            }
        });
    }//GEN-LAST:event_BorrowerDetailsButtonActionPerformed

    private void ClerkDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClerkDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails(2).setVisible(true);
            }
        });
    }//GEN-LAST:event_ClerkDetailsActionPerformed

    private void LibrarianDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarianDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails(3).setVisible(true);
            }
        });
    }//GEN-LAST:event_LibrarianDetailsActionPerformed

    private void BookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllBooks().setVisible(true);
            }
        });
    }//GEN-LAST:event_BookDetailsActionPerformed

    private void DvdDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DvdDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllDvds().setVisible(true);
            }
        });
    }//GEN-LAST:event_DvdDetailsActionPerformed

    private void LoanDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanDetails().setVisible(true);
            }
        });
    }//GEN-LAST:event_LoanDetailsActionPerformed

    private void UserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSearchActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //this.setDefaultCloseOperation(SearchUserByID.DO_NOTHING_ON_CLOSE);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUser().setVisible(true);
            }
        });
    }//GEN-LAST:event_UserSearchActionPerformed

    private void ViewProfileInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileInfoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProfileInfo().setVisible(true);
            }
        });
    }//GEN-LAST:event_ViewProfileInfoActionPerformed

    private void ChangeUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUserPasswordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeUserPassword().setVisible(true);
            }
        });
    }//GEN-LAST:event_ChangeUserPasswordActionPerformed

    private void ChangeYourPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeYourPasswordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeYourPassword().setVisible(true);
            }
        });
    }//GEN-LAST:event_ChangeYourPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JButton AddUser;
    private javax.swing.JButton AllBookAvailable;
    private javax.swing.JButton AllDvdAvailable;
    private javax.swing.JButton AllPendingLoans;
    private javax.swing.JButton BookDetails;
    private javax.swing.JButton BorrowerDetailsButton;
    private javax.swing.JButton ChangeUserPassword;
    private javax.swing.JButton ChangeYourPassword;
    private javax.swing.JButton CheckInItem;
    private javax.swing.JButton CheckOutItem;
    private javax.swing.JButton ClerkDetails;
    private javax.swing.JButton DvdDetails;
    private javax.swing.JButton EditItem;
    private javax.swing.JButton EditUser;
    private javax.swing.JButton LibrarianDetails;
    private javax.swing.JButton LoanDetails;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton RemoveItem;
    private javax.swing.JButton RemoveUser;
    private javax.swing.JButton SearchItem;
    private javax.swing.JButton SearchLoan;
    private javax.swing.JButton UserSearch;
    private javax.swing.JButton ViewProfileInfo;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
